#!/bin/bash
# Script to start an SSH server on the raspberry pi
# This script prints the RSA and DSA key of the server as well

SERVER_ADDR4=$(ifconfig wlan0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1 }');
SERVER_ADDR6=$(ifconfig wlan0 | grep 'inet6 addr:' | cud -d: -f2 | awk '{ print $1 }');

echo -e "$(tput bold)========================================$(tput sgr0)";
echo "Starting SSH server...";

sudo /etc/init.d/ssh start;

RSA_HOST_KEY=$(ssh-keygen -l -f /etc/ssh/ssh_host_rsa_key | awk '{print $2}');
DSA_HOST_KEY=$(ssh-keygen -l -f /etc/ssh/ssh_host_dsa_key | awk '{print $2}');

echo "SSH Server started and running";
printf "\n"
echo -e "Server name:    $(tput bold)$(tput setaf 2)pi@$SERVER_ADDR4$(tput sgr0)";
echo -e "                $(tput bold)$(tput setaf 3)pi@$SERVER_ADDR6$(tput sgr0)";
echo -e "Host RSA Key:   $(tput setaf 2)$RSA_HOST_KEY$(tput sgr0)";
echo -e "Host DSA Key:   $(tput setaf 2)$DSA_HOST_KEY$(tput sgr0)";

echo -e "$(tput bold)========================================$(tput sgr0)";
