#!/bin/bash
# This script closes the SSH server

SERVER_ADDR=$(ifconfig wlan0 | grep 'inet addr:' | cut -d: -f2 | awk '{print $1}');

echo -e "$(tput bold)========================================$(tput sgr0)";
echo -e "Stopping SSH server $(tput bold)$(tput setaf 1)pi@$SERVER_ADDR$(tput sgr0)";
printf "\n";

sudo /etc/init.d/ssh stop;

printf "\n";
echo "DONE";
echo -e "$(tput bold)========================================$(tput sgr0)";
